# Generated by Django 4.1.6 on 2023-02-02 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=125, unique=True),
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('user_email', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('case_state', models.CharField(choices=[('wait', 'wait'), ('way_to_catch', 'way_to_catch'), ('arrived', 'arrived'), ('catched', 'catched'), ('on_road', 'on_road'), ('finished', 'finished'), ('canceled', 'canceled')], default='', max_length=20)),
                ('on_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('on_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('on_address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('off_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('off_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('off_address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('case_money', models.IntegerField(blank=True, default=0, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('confirm_time', models.DateTimeField(blank=True, null=True)),
                ('arrived_time', models.DateTimeField(blank=True, null=True)),
                ('catched_time', models.DateTimeField(blank=True, null=True)),
                ('off_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
