# Generated by Django 4.1.6 on 2023-02-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0002_remove_user_phone_user_email_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='car_id_number',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='car_model',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='driver_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
