# Generated by Django 4.1.6 on 2023-02-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0003_case_car_id_number_case_car_model_case_driver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_english',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='off_address_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='on_address_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
