# Generated by Django 4.1.6 on 2023-02-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0004_case_is_english_case_off_address_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='expect_minutes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
