# Generated by Django 4.1.6 on 2023-02-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0006_case_case_type_case_reserve_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(choices=[('direct', 'direct'), ('reserve', 'reserve')], default='direct', max_length=20),
        ),
    ]
